[GENERAL]
# file name of coefficients for the model
SRC_COEFS = 
# file name of conversion table for the model
SRC_CONV_TBL = 
# debug mode used for development
DEBUG = False
# default CRS if not found in the input data
CRS = EPSG:4326
# default CRS for calculations and internal use
CRS_CALC = EPSG:6875
TZ_LOCAL = Europe/Rome
TZ_CALC = UTC

[OUTPUT]
# output aggregation interval in minutes
OUTPUT_AGG_INT = 15
# output state compression method
# blosclz, lz4, lz4hc, snappy, zlib, zstd, gzip, bz2, zip, lzma or None (lz4 default)
OUTPUT_STATE_COMPRESSION = gzip
# compression level for output state (1-9) (default 5)
OUTPUT_STATE_LEVEL_COMPRESSION = 5
# output of individual results
OUTPUT_IND_RES = True
# percentage of vehicles to monitor for individual results
MONITORED_VEH = 30

[WEB_SERVER]
# web server host address
WEB_SERVER_HOST = 0.0.0.0
# web server port
WEB_SERVER_PORT = 5000
# web server debug mode
WEB_SERVER_DEBUG = False

[DATABASE]
# internal database connection string (tracking execution, logging, etc.)
#DATABASE_URL = postgresql+psycopg2://postgres:lDvdc15dcd5@192.168.133.80:5432/m4i
DATABASE_URL = sqlite:///model4italy.db

[DATABASE_SETTINGS]
# database for the model settings
DB_SETTINGS_USE = False
DB_SETTINGS_URL = sqlite:///settings.db

[LOGGING]
# logging configuration
LOG_USE = True
# log name
LOG_NAME = m4i
# log level
LOG_LEVEL = DEBUG
# log on internal database
LOG_ON_DATABASE = True
# log on console
LOG_ON_CONSOLE = True
# log on file
LOG_ON_FILE = True
# log if the execution is tracked
LOG_EXECUTION_FORMAT = %%(asctime)s | %%(last_elapsed).2f/%%(elapsed).2fs | %%(levelname)s | %%(name)s | %%(execution_id)s | %%(message)s
# log format if execution is not tracked
LOG_FORMAT = %%(asctime)s | %%(levelname)s | %%(name)s | %%(message)s
# log directory for file logging
LOG_DIR = log

[IPC]
# inter-process communication settings
IPC_USE = True
# IPC bucket name. This is used to realize unique names for the IPC channels and variables: es: foo -> bucket:foo.
IPC_BUCKET = m4i
# IPC backend to use: local for local IPC, redis for redis IPC
IPC_BACKEND = local 
# address of the IPC server (default localhost)
IPC_HOST = localhost 
# redis server port or free port for local
IPC_PORT = 16379 
# redis db number. not used for local
IPC_DB = 0 
# compression method for data tranfer # blosclz, lz4, lz4hc, snappy, zlib, zstd, gzip, bz2, zip, lzma or None (lz4 default)
# the data are serialized as pickle with dill library and compressed
IPC_COMPRESSION = lz4 
# compression level for data tranfer (1-9) (default 5)
IPC_COMPRESSION_LEVEL = 5 

[PARALLEL]
# parallel execution settings
PARALLEL_USE = True
# number of parallel processes n=0 -> max available, n<0 ->number of available cores - n, n>0 -> max(number of corse and n)
PARALLEL_NUMCPUS = 16
# ray or None
PARALLEL_ENGINE = ray
# address of the cluster (default auto) (auto,local,or ip address ray://ip:port)
#PARALLEL_CLUSTER_ADDRESS = auto
PARALLEL_CLUSTER_ADDRESS = local


[SIMULATOR]
# simulator settings
# simulation step in seconds
SIMU_STEP = 6
# car length in meters
CAR_LENGTH = 5
# minimum speed in km/h
MIN_SPEED = 4
# aggregation interval in seconds for tracking
AGG_INT = 5
# simulation parameters
LT1 = 0
LT2 = 0

[ASSIGNMENT]
# assignment settings
# default equivalent class factor for the assignment
CLASS_EQ_FACT = {'c': 1, 'h': 2}
# maximum number of iterations for the assignment
MSA_MAX_ITE = 3
# relative gap for the assignment
MSA_RGAP = 0.01
# maximum number of paths for the MSA algorithm
MSA_K = 3
# maximum timeslice for the MSA algorithm in seconds
MSA_MAX_TIMESLICE = 180
# maximum number of CPUs for the MSA algorithm (PARALLEL_NUMCPUS is maximum number of CPUs available)
# n=0 -> max available, n<0 ->number of available cores - n, n>0 -> max(number of corse and n)
MSA_SPP_NUMCPUS = 0
# MSA balancing factor to evaluate 1/k shifted flows
# <= 0 indicates that the balance of the MSA starts with k=MSA_K, if >0 indicates that k=indicated value
MSA_K_BALANCING = -1
# Time interval for the assignment in minutes (default 15). OD matrix and paths are updated every DELTA_T minutes.
DELTA_T = 15
# Save at the end /laod at begin the paths in assignment algorithm (default: false).
SAVE_PATHS = False
LOAD_PATHS = False
# Save at the end/laod at begin the graph in assignment algorithm (default: false).
SAVE_GRAPH = False
LOAD_GRAPH = False
# Simulation preload period/Post simulation period (default: 60).
MSA_PRELOAD = 0
MSA_POSTLOAD = 0
# 
USE_OBSERVED_PATHS = True

[OD_ESIMATION]
OD_ESTIMATION_WHISKERS = 60
OD_ESTIMATION_MAX_ITE = 2
OD_ESTIMATION_RGAP = 0.01
OD_ESTIMATION_MSA_MAX_ITE = 3
OD_ESTIMATION_MSA_K = 3
OD_ESTIMATION_MSA_RGAP = 0.001
OD_ESTIMATION_MSA_TIMESLICE = 60
OD_ESTIMATION_USE_OBSERVED_PATHS = True
OD_ESTIMATION_GAMMA1 = 0
OD_ESTIMATION_GAMMA2 = 1
OD_ESTIMATION_GAMMA3 = 1
    # Parametri della ricerca del passo con metodo della sezione aurea
OD_ESTIMATION_ITESA = 100
# Estremo inferiore della ricerca monodimensionale
OD_ESTIMATION_LAMBDA_LB= 0  
# Estremo superiore
OD_ESTIMATION_LAMBDA_UB = 0.05 
# Soglia di arresto dell'ottimizzazione monodimensionale 
OD_ESTIMATION_EPS = 0.000001  
OD_ESTIMATION_EPS2 = 10
# segmento minore della sezione aurea
OD_ESTIMATION_SA = 0.362  
# Pesi interni ODseed - si potrebbero inserire come input esternamente alla classe StimaOD?
    

[FCD_SERVER]
FCD_SERVER_MAP_MATCHING=True
FCD_SERVER_TRIPS=True
FCD_SERVER_ROUTING=True
FCD_SERVER_UPDATE_SPEED=True
# timeslice di esecuzione in minuti
FCD_SERVER_FCD_TIMESLICE = 5
# timeslice di esecuzione in minuti
FCD_SERVER_FCD_TIMESLICE_OFFLINE = 120
# memoria in minuti per cui vengono memorizzati i dati e cammini
FCD_SERVER_FCD_HORIZON = 60
FCD_SERVER_SHARE_DATA_ONLINE = True
FCD_SERVER_WRITE_OUTPUT = True

[FCD_SPEED]
FCD_SPEED_AGGREGATION_INTERVAL = 60

[FCD_MAP_MATCHING]
FCD_MAP_MATCHING_CPUS = 0
FCD_MAP_MATCHING_MAX_DISTANCE=50
FCD_MAP_MATCHING_MAX_ANGLE=45


[FCD_ROUTING]
FCD_ROUTING_CPUS = 0
FCD_ROUTING_START_FROM_ZONE = 1
FCD_ROUTING_END_TO_ZONE = 1
FCD_ROUTING_AGGRATION_INTERVAL = 15

[FCD_TRIPS]
FCD_TRIPS_CPUS = 0
FCD_TRIPS_SIGNAL_BREAK_MAX_DT = 900
FCD_TRIPS_SIGNAL_BREAK_DT = 300
# 2 km/h
FCD_TRIPS_SIGNAL_BREAK_V = 0.5555555555555556  
FCD_TRIPS_STOP_O_DS = 50
FCD_TRIPS_STOP_D_DS = 50
FCD_TRIPS_SIGNAL_CONT_DT = 600
# 0.5 km/h
FCD_TRIPS_SIGNAL_CONT_V = 0.1388888888888889  
# 250 km/h
FCD_TRIPS_MAX_V3 = 69.44444444444444  
FCD_TRIPS_MAX_DISTANCE_OVERRIDE_POSITION_FIRST_POINT = 200
FCD_TRIPS_MIN_LENGTH = 100
FCD_TRIPS_MIN_TIME = 1
FCD_TRIPS_REMOVE_STOPS = False
FCD_TRIPS_MAX_DISTANCE_BETWEEN_DATA = 20000
FCD_TRIPS_MAX_DELTA_PROGR = 20000
