[GENERAL]
SRC_COEFS = dati/GrafoRoma/coefficients.json
SRC_CONV_TBL = 
NUMCPU = 4
PARALLEL_ENGINE = ray
DEBUG = False

[SIMULATOR]
SIMU_STEP = 6
CAR_LENGTH = 5
MIN_SPEED = 4
AGG_INT = 0.1
LT1 = 0
LT2 = 0

[ASSIGNMENT]
CLASS_EQ_FACT = {'c': 1, 'h': 2}
MSA_MAX_ITE = 3
MSA_RGAP = 0.01
MSA_K = 3
MSA_MAX_TIMESLICE = 180
DELTA_T = 15
SAVE_PATHS = False
LOAD_PATHS = False
SAVE_GRAPH = False
LOAD_GRAPH = False
MSA_PRELOAD = 0
MSA_POSTLOAD = 0

[OD_ESIMATION]
OD_ESTIMATION_PRELOAD = 60
OD_ESTIMATION_MAX_ITE = 2
OD_ESTIMATION_RGAP = 0.01
OD_ESTIMATION_MSA_MAX_ITE = 3
OD_ESTIMATION_MSA_K = 3
OD_ESTIMATION_MSA_RGAP = 0.001
OD_ESTIMATION_MSA_TIMESLICE = 60

[OUTPUT]
OUTPUT_AGG_INT = 15

[FLASK]
FLASK_HOST = 0.0.0.0
FLASK_PORT = 5000
FLASK_DEBUG = True

[DATABASE]
#DATABASE_URL = postgresql+psycopg2://postgres:lDvdc15dcd5@192.168.133.80:5432/model4italy
DATABASE_URL = sqlite:///model4italy.db

[DATABASE_SETTINGS]
DB_SETTINGS_USE = False
DB_SETTINGS_TYPE = sqlite
DB_SETTINGS_DRIVER = sqlite
DB_SETTINGS_USER = 
DB_SETTINGS_PASS = 
DB_SETTINGS_HOST = 
DB_SETTINGS_PORT = 
DB_SETTINGS_NAME = settings.db

[LOGGING]
USE_LOG = True
DIR_LOG = log