[GENERAL]
SRC_COEFS = dati/GrafoRoma/coefficients.json
SRC_CONV_TBL = 
DEBUG = False
CRS = EPSG:4326
CRS_CALC = EPSG:6875

[OUTPUT]
OUTPUT_AGG_INT = 15
OUTPUT_STATE_COMPRESSION = "gzip"

[FLASK]
FLASK_HOST = 0.0.0.0
FLASK_PORT = 5000
FLASK_DEBUG = True

[DATABASE]
#DATABASE_URL = postgresql+psycopg2://postgres:lDvdc15dcd5@192.168.133.80:5432/m4i
DATABASE_URL = sqlite:///model4italy.db

[DATABASE_SETTINGS]
DB_SETTINGS_USE = False
DB_SETTINGS_TYPE = sqlite
DB_SETTINGS_DRIVER = sqlite
DB_SETTINGS_USER = 
DB_SETTINGS_PASS = 
DB_SETTINGS_HOST = 
DB_SETTINGS_PORT = 
DB_SETTINGS_NAME = settings.db

[LOGGING]
LOG_USE = True
LOG_NAME = M4I
LOG_LEVEL = DEBUG
LOG_EXECUTION_FORMAT = %%(execution_id)s - %%(asctime)s | %%(last_elapsed).2f/%%(elapsed).2fs | %%(levelname)s | %%(name)s | %%(message)s
LOG_FORMAT = %%(asctime)s | %%(levelname)s | %%(name)s | %%(message)s
LOG_DIR = log
LOG_ON_DATABASE = True
LOG_ON_CONSOLE = True
LOG_ON_FILE = True

[IPC]
IPC_USE = True
IPC_BUKCET = m4i
# local or redis
IPC_BACKEND = local 
# localhost or redis server address
IPC_HOST = localhost 
# redis server port or free port for local
IPC_PORT = 16379 
# redis db number or not used for local
IPC_DB = 0 
# compression method for data tranfer # "blosclz", "lz4", "lz4hc", "snappy", "zlib", "zstd", "gzip", "bz2", "zip", "lzma" or None (lz4 default)
IPC_COMPRESSION = lz4 
# compression level for data tranfer (1-9) (default 5)
IPC_COMPRESSION_LEVEL = 5 

[PARALLEL]
PARALLEL_USE = True
# number of parallel processes (default 16)
PARALLEL_NUMCPU = 0
# ray or None
PARALLEL_ENGINE = ray 
# address of the cluster (default auto) (auto,local,or ip address ray://ip:port)
#PARALLEL_CLUSTER_ADDRESS = auto
PARALLEL_CLUSTER_ADDRESS = local


[SIMULATOR]
SIMU_STEP = 6
CAR_LENGTH = 5
MIN_SPEED = 4
AGG_INT = 5
LT1 = 0
LT2 = 0

[ASSIGNMENT]
CLASS_EQ_FACT = {'c': 1, 'h': 2}
MSA_MAX_ITE = 3
MSA_RGAP = 0.01
MSA_K = 3
MSA_MAX_TIMESLICE = 180
DELTA_T = 15
SAVE_PATHS = False
LOAD_PATHS = False
SAVE_GRAPH = False
LOAD_GRAPH = False
MSA_PRELOAD = 0
MSA_POSTLOAD = 0


[OD_ESIMATION]
OD_ESTIMATION_PRELOAD = 60
OD_ESTIMATION_MAX_ITE = 2
OD_ESTIMATION_RGAP = 0.01
OD_ESTIMATION_MSA_MAX_ITE = 3
OD_ESTIMATION_MSA_K = 3
OD_ESTIMATION_MSA_RGAP = 0.001
OD_ESTIMATION_MSA_TIMESLICE = 60

[FCD]
# timeslice di esecuzione in minuti
FCD_TIMESLICE = 5
# memoria in minuti per cui vengono memorizzati i dati e cammini
FCD_HORIZON = 60
FCD_MAP_MATCHING_CPUS = 32
FCD_PATH_MATCHING_CPUS = 32
FCD_MAP_MATCHING_MAX_DISTANCE=50
FCD_MAP_MATCHING_MAX_ANGLE=45
FCD_CRS_DATA = EPSG:4326
FCD_CRS_CALC = EPSG:6875
FCD_PATH_START_FROM_ZONE = 1
FCD_PATH_END_TO_ZONE = 1
FCD_PATH_AGGRATION_INTERVAL = 15